<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPRURYAW7112" name="QuadrateParameter6" tests="1" failures="1" timestamp="6 Feb 2019 15:43:21 GMT" time="0.0" errors="0">
  <testcase name="testForFailing" time="0.0" classname="jar.ExpectedExeption">
    <failure type="org.testng.TestException" message="
Expected exception java.lang.Exception but got org.testng.TestException: 
Method ExpectedExeption.testForFailing(double)[pri:0, instance:jar.ExpectedExeption@4b2bac3f] should have thrown an exception of class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method ExpectedExeption.testForFailing(double)[pri:0, instance:jar.ExpectedExeption@4b2bac3f] should have thrown an exception of class java.lang.Exception
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
Method ExpectedExeption.testForFailing(double)[pri:0, instance:jar.ExpectedExeption@4b2bac3f] should have thrown an exception of class java.lang.Exception
	... 25 more
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- testForFailing -->
</testsuite> <!-- QuadrateParameter6 -->
